# Generated by Django 2.0.6 on 2018-06-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('memeOn', models.BooleanField()),
                ('newMenuItemsOn', models.BooleanField()),
                ('dailyDealsOn', models.BooleanField()),
                ('igUsername', models.TextField()),
                ('igPassword', models.TextField()),
            ],
        ),
    ]
