# Generated by Django 2.0.6 on 2018-06-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='weedmapsSlug',
            field=models.TextField(default='Not given'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='igPassword',
            field=models.TextField(default='Not given'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='igUsername',
            field=models.TextField(default='Not given'),
        ),
    ]
