# Generated by Django 2.0.6 on 2018-06-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20180610_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='dailyDealsOn',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='memeOn',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='newMenuItemsOn',
            field=models.BooleanField(default=True),
        ),
    ]
