# Generated by Django 2.0.6 on 2018-06-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20180610_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispensary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensaryID', models.IntegerField()),
                ('dateAdded', models.DateTimeField()),
                ('name', models.TextField()),
                ('prices', models.TextField()),
            ],
        ),
    ]
