# Generated by Django 2.0.6 on 2018-06-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_dispensary_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensary',
            name='tipe',
            field=models.TextField(default='dispensary'),
        ),
    ]
