# Generated by Django 2.0.6 on 2018-06-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_dispensary_tipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='botPID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='botStatus',
            field=models.BooleanField(default=False),
        ),
    ]
