# Generated by Django 2.0.6 on 2018-06-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensary',
            name='wmid',
            field=models.IntegerField(default=0),
        ),
    ]
